### ISSUE TITLE
java.lang.RuntimeException: Error: no more data

### ISSUE THREAD

**Issue by j2ghz** [IvanVolosyuk/diskusage#33]
If I select anything else than storage/emulated/0 or app storage I get this error. root access granted.

**Comment by j2ghz** [comment]
v 3.4.2 on android 6.0.1

**Comment by ahstro** [comment]
Fixed in later versions althouh they're not available through F-Droid

**Comment by Canice-James** [comment]
Although I'm on the latest version I'm still experiencing this problem. Phone: Rooted LG G4 stylus
